### ISSUE TITLE
Add support for specifying a different port 

### ISSUE THREAD

**Issue by kylekirkby** [linaro-its/jekyll-build-container#45]
Hi all,

It would be great if you could either point me in the right direction for building the sites to a different port or help in adding support for this, as more often than not, I find myself working on a few sites concurrently. As a result, I get errors like this:

```
 kyle@gibson  ~/Documents/websites/linaro.org   master ⍟8  JEKYLLSITEBUILD=5df0b73 JEKYLL_ENV="staging" JEKYLL_ACTION='serve' ./build-site.sh
docker: Error response from daemon: driver failed programming external connectivity on endpoint naughty_cohen (6f3c4786d6f101126132c32d9a53700083f126481d51c5c1a56bfedd2fc058db): Bind for 0.0.0.0:4000 failed: port is already allocated.
```

Something like a `JEKYLL_PORT` variable would be super useful! I thought I saw this before but now can't see it in this projects wiki docs.

BR,

Kyle

**Comment by kylekirkby** [comment]
@pcolmer - Bump : )

**Comment by pcolmer** [comment]
@kylekirkby this doesn't need any changes to the container - just a change to the `build-site.sh` script in the website repo.

Can you please fetch https://github.com/linaro-its/container-scripts/blob/feature/ITS-1649/build-site.sh and test that on one of the sites? The variable is called `JEKYLL_PORT` per your suggestion.

**Comment by kylekirkby** [comment]
> @kylekirkby this doesn't need any changes to the container - just a change to the `build-site.sh` script in the website repo.
> 
> Can you please fetch https://github.com/linaro-its/container-scripts/blob/feature/ITS-1649/build-site.sh and test that on one of the sites? The variable is called `JEKYLL_PORT` per your suggestion.

Sure! Thanks @pcolmer !

**Comment by kylekirkby** [comment]
@pcolmer - the updated `build.sh` script works as expected other than the server address in the build output shows as http://0.0.0.0:4000 still. Is this something we can change?

```
 JEKYLL_PORT=4001 JEKYLL_ACTION=serve ./build-site.sh ✔
Container built by bamboo.linaro.org: CON-JBC0-JOB1-11
Single-repo site - proceeding with normal processing.
Validating source files
Configuration file: /srv/source/_config.yml
Configuration file: /srv/source/_config-staging.yml
 Theme Config file: /var/lib/gems/2.5.0/gems/jumbo-jekyll-theme-5.6.9.2/_config.yml
         AutoPages: Disabled/Not configured in site.config.
        Pagination: Complete, processed 6 pagination page(s)
       Jekyll Feed: Generating feed for posts
  Your test results are in. Everything looks fine.
Building site
Configuration file: /srv/source/_config.yml
Configuration file: /srv/source/_config-staging.yml
 Theme Config file: /var/lib/gems/2.5.0/gems/jumbo-jekyll-theme-5.6.9.2/_config.yml
            Source: /srv/source
       Destination: staging.linaro.org
 Incremental build: disabled. Enable with --incremental
      Generating... 
         AutoPages: Disabled/Not configured in site.config.
        Pagination: Complete, processed 6 pagination page(s)
       Jekyll Feed: Generating feed for posts
                    done in 169.007 seconds.
 Auto-regeneration: enabled for '/srv/source'
    Server address: http://0.0.0.0:4000
  Server running... press ctrl-c to stop.

```
